put commit hook back since i obviously dont understand bash scripts

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,21 +1,11 @@
 #!/bin/sh
 
-if [[{ git status -b --porcelain | grep "## master" }]]
+node test/test_basic.js
+# get return code
+# HT http://stackoverflow.com/a/90435/351392
+rc=$?
+
+if [[ $rc != 0 ]]
 then
- 
-  node test/test_basic.js
-  # get return code
-  # HT http://stackoverflow.com/a/90435/351392
-  rc=$?
-
-  if [[ $rc != 0 ]]
-  then
     exit 1
-  fi
-
-else
-
-  { echo "Not on master so not doing commit tests!"; }
-
 fi
-
